import os

from metrics.base import metric


@metric
def languages_in_a_commit(graph):
    """Computes the number of different file languages of the commits."""

    result = []
    for commit in graph.iterate_commits():
        file_types = set()
        for file_name in graph.commit_files[commit]:
            file_extension = os.path.splitext(file_name)[1][1:]

            if file_name in FILE_NAME_MAPPING:
                file_type = FILE_NAME_MAPPING[file_name]
            elif file_extension in FILE_EXTENSION_MAPPING:
                file_type = FILE_EXTENSION_MAPPING[file_extension]
            else:
                file_type = u"Other"
            file_types.add(file_type)
        result.append(len(file_types))
    return result


FILE_NAME_MAPPING = {
    'CMakeLists.txt': u"CMake",
    'Gnumakefile': u"make",
    'Makefile': u"make",
    'build.xml': u"Ant/XML",
    'gnumakefile': u"make",
    'makefile': u"make",
    'pom.xml': u"Maven/XML"
}

FILE_EXTENSION_MAPPING = {
    'BAT': u"DOS Batch",
    'C': u"C++",
    'CBL': u"COBOL",
    'CMakeLists.txt': u"CMake",
    'COB': u"COBOL",
    'F': u"Fortran 77",
    'F77': u"Fortran 77",
    'F90': u"Fortran 90",
    'F95': u"Fortran 95",
    'Gnumakefile': u"make",
    'H': u"C/C++ Header",
    'Makefile': u"make",
    'PL': u"Perl",
    'S': u"Assembly",
    'SBL': u"Softbridge Basic",
    'SQL': u"SQL",
    'VB': u"Visual Basic",
    'VBA': u"Visual Basic",
    'VBS': u"Visual Basic",
    'VHD': u"VHDL",
    'VHDL': u"VHDL",
    'XML': u"XML",
    'XSD': u"XSD",
    'XSL': u"XSLT",
    'XSLT': u"XSLT",
    'abap': u"ABAP",
    'ac': u"m4",
    'ada': u"Ada",
    'adb': u"Ada",
    'ads': u"Ada",
    'adso': u"ADSO/IDSM",
    'ahk': u"AutoHotkey",
    'am': u"make",
    'ample': u"AMPLE",
    'as': u"ActionScript",
    'asa': u"ASP",
    'asax': u"ASP.Net",
    'ascx': u"ASP.Net",
    'asm': u"Assembly",
    'asmx': u"ASP.Net",
    'asp': u"ASP",
    'aspx': u"ASP.Net",
    'awk': u"awk",
    'bas': u"Visual Basic",
    'bash': u"Bourne Again Shell",
    'bat': u"DOS Batch",
    'build': u"NAnt scripts",
    'build.xml': u"Ant",
    'c': u"C",
    'cbl': u"COBOL",
    'cc': u"C++",
    'ccs': u"CCS",
    'cfc': u"ColdFusion CFScript",
    'cfm': u"ColdFusion",
    'clj': u"Clojure",
    'cljs': u"ClojureScript",
    'cls': u"Visual Basic",
    'cmake': u"CMake",
    'cob': u"COBOL",
    'coffee': u"CoffeeScript",
    'component': u"Visualforce Component",
    'config': u"ASP.Net",
    'cpp': u"C++",
    'cs': u"C#",
    'csh': u"C Shell",
    'cshtml': u"Razor",
    'csproj': u"MSBuild scripts",
    'css': u"CSS",
    'ctl': u"Visual Basic",
    'cxx': u"C++",
    'd': u"D",
    'da': u"DAL",
    'dart': u"Dart",
    'data.sql': u"SQL Data",
    'def': u"Teamcenter def",
    'dmap': u"NASTRAN DMAP",
    'dofile': u"AMPLE",
    'dpr': u"Pascal",
    'dsr': u"Visual Basic",
    'dtd': u"DTD",
    'ec': u"C",
    'el': u"Lisp",
    'erl': u"Erlang",
    'exp': u"Expect",
    'f': u"Fortran 77",
    'f77': u"Fortran 77",
    'f90': u"Fortran 90",
    'f95': u"Fortran 95",
    'fmt': u"Oracle Forms",
    'focexec': u"Focus",
    'frm': u"Visual Basic",
    'gant': u"Groovy",
    'gnumakefile': u"make",
    'go': u"Go",
    'groovy': u"Groovy",
    'h': u"C/C++ Header",
    'hh': u"C/C++ Header",
    'hpp': u"C/C++ Header",
    'hrl': u"Erlang",
    'hs': u"Haskell",
    'htm': u"HTML",
    'html': u"HTML",
    'i3': u"Modula3",
    'idl': u"IDL",
    'ig': u"Modula3",
    'il': u"SKILL",
    'ils': u"SKILL++",
    'ino': u"Arduino Sketch",
    'ism': u"InstallShield",
    'itk': u"Tcl/Tk",
    'java': u"Java",
    'jcl': u"JCL",
    'jl': u"Lisp",
    'js': u"Javascript",
    'jsf': u"JavaServer Faces",
    'jsp': u"JSP",
    'ksc': u"Kermit",
    'ksh': u"Korn Shell",
    'l': u"lex",
    'less': u"LESS",
    'lhs': u"Haskell",
    'lisp': u"Lisp",
    'lsp': u"Lisp",
    'lua': u"Lua",
    'm3': u"Modula3",
    'm4': u"m4",
    'makefile': u"make",
    'master': u"ASP.Net",
    'met': u"Teamcenter met",
    'mg': u"Modula3",
    'ml': u"OCaml",
    'mli': u"OCaml",
    'mll': u"OCaml",
    'mly': u"OCaml",
    'mm': u"Objective C++",
    'mps': u"MUMPS",
    'mth': u"Teamcenter mth",
    'mxml': u"MXML",
    'oscript': u"LiveLink OScript",
    'p': u"Pascal",
    'pad': u"Ada",
    'page': u"Visualforce Page",
    'pas': u"Pascal",
    'pcc': u"C++",
    'pcl': u"Patran Command Language",
    'pde': u"Arduino Sketch",
    'perl': u"Perl",
    'pfo': u"Fortran 77",
    'pgc': u"C",
    'php': u"PHP",
    'php3': u"PHP",
    'php4': u"PHP",
    'php5': u"PHP",
    'pig': u"Pig Latin",
    'pl': u"Perl",
    'plh': u"Perl",
    'plx': u"Perl",
    'pm': u"Perl",
    'pom': u"Maven",
    'pom.xml': u"Maven",
    'pp': u"Pascal",
    'pro': u"IDL",
    'ps1': u"PowerShell",
    'psql': u"SQL",
    'py': u"Python",
    'pyx': u"Cython",
    'qml': u"QML",
    'rb': u"Ruby",
    'rex': u"Oracle Reports",
    'rexx': u"Rexx",
    'rhtml': u"Ruby HTML",
    'rs': u"Rust",
    's': u"Assembly",
    'sass': u"SASS",
    'sbl': u"Softbridge Basic",
    'sc': u"Lisp",
    'scala': u"Scala",
    'scm': u"Lisp",
    'scss': u"SASS",
    'sed': u"sed",
    'ses': u"Patran Command Language",
    'sh': u"Bourne Shell",
    'sitemap': u"ASP.Net",
    'smarty': u"Smarty",
    'spc.sql': u"SQL Stored Procedure",
    'spoc.sql': u"SQL Stored Procedure",
    'sproc.sql': u"SQL Stored Procedure",
    'sql': u"SQL",
    'startup': u"AMPLE",
    'sv': u"Verilog-SystemVerilog",
    'svh': u"Verilog-SystemVerilog",
    'tcl': u"Tcl/Tk",
    'tcsh': u"C Shell",
    'tk': u"Tcl/Tk",
    'tpl': u"Smarty",
    'trigger': u"Apex Trigger",
    'udf.sql': u"SQL Stored Procedure",
    'v': u"Verilog-SystemVerilog",
    'vala': u"Vala",
    'vapi': u"Vala Header",
    'vb': u"Visual Basic",
    'vba': u"Visual Basic",
    'vbs': u"Visual Basic",
    'vhd': u"VHDL",
    'vhdl': u"VHDL",
    'vim': u"vim script",
    'wdproj': u"MSBuild scripts",
    'webinfo': u"ASP.Net",
    'xaml': u"XAML",
    'xhtml': u"JavaServer Faces",
    'xml': u"XML",
    'xsd': u"XSD",
    'xsl': u"XSLT",
    'xslt': u"XSLT",
    'y': u"yacc",
    'yaml': u"YAML",
    'yml': u"YAML"
}